apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-client-deployment
  labels:
    app: yolo-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo-client
  template:
    metadata:
      labels:
        app: yolo-client
    spec:
      containers:
      - name: yolo-client
        image: ombongimn/yoloclient-img:v1.2
        ports:
        - containerPort: 3000
        env:
        - name: yolo-backend
          value: http://yolo-backend:5000/
---
apiVersion: v1
kind: Service
metadata:
  name: yolo-client-service
spec:
  type: LoadBalancer
  selector:
    app: yolo-client
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000